GET http://localhost:3000/devices
###

GET http://localhost:3000/device?id=3
###

POST http://localhost:3000/devices
Content-Type: application/json

{
  "id":"3",
  "name":"Mede temperatura sala 203",
  "unidade":"C"
}

###

DELETE https://https://localhost:3000/

###

UPDATE https://https://localhost:3000/