GET http://localhost:3000/devices
###

GET http://localhost:3000/device?id=iot0988
###

POST http://localhost:3000/devices
Content-Type: application/json

{
  "id":"3",
  "name":"Mede temperatura sala 203",
  "unidade":"C"
}

###

DELETE http://localhost:3000/device?id=iot0988

###

PUT http://https://localhost:3000/devices
Content-Type: application/json

{
  "id":"3",
  "name":"Mede temperatura sala 203",
  "unidade":"C"
}
