GET http://localhost:3000/devices
###

GET http://localhost:3000/device?id=4
###

POST http://localhost:3000/devices
Content-Type: application/json

{
  "id":"4",
  "name":"Mede temperatura sala 204",
  "unidade":"C"
}

###

DELETE http://localhost:3000/device?id=4

###

PUT http://localhost:3000/devices
Content-Type: application/json

{
  "id":"4",
  "name":"Mede temperatura sala 208",
  "unidade":"F"
}
